lang: c
script: ./travis-ci.sh
env:
  secure: "Ishe3/mJQyTNbzsKt4ZJZxY5qR+CsWPe0iOmxh1olKw5KkqDAPm9uj6/rV0cVYbqE6x4VhdtxWv3HJ7dYfSt83pysuP5z/Wap+HEIxa4d9Q5B7dFm6mhRb3Y4OJmZfqZ3Uehkxrrgk/2iZgzuvqhD6M+igCTGNlHdhNKDT8b6Nn7SSPj3mXHmBAm3LdqEzaMHVir7ApDHDN6fvmTqmOwCQJa5fqFecn9ThX6nQmehnxAEdwWGvyNZQd3+iEb8mTwPHK9eCvvKFBxix3L2Dsaplf/uB59YO5Vjw6mTpHv1XXqfN4+Yjmbq+2+bzmCDBQrbY/08yongOjBc0JwbyX8pzKKo99iWSuOL9IlmXehUQLZlMS4v1Cvx9+Rs9LsdhcTHHod95o+anQOQQV5eNu6uRSc+mH+MIwPk/VKM5Snzh2gtCi9tQizOVPt7HdmMsfrCh70Q11m09u48g2yj32q4gLnAstlDgF7EriJFZQmFjeU9/2x/vR5OBLJWjq50hQXzppEXCLGxnhfQdIQLe5qJtbcXaY6h3Xee8PHzEeO3jna6rQR/ddDn46sLG93Jhrw11Nqz8PHWCe96vgEhhJ6/+8JWEShgjcSG/FdU7PbYUbXLwbulwJb33RYWmp9qijkrnoO2i0xIVHw58WWmSvP2wcHp4FjcLtVDOFBDFEbjG8="
notifications:
  irc:
    - "irc.freenode.org#rerun"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq markdown
 - sudo apt-get install -qq build-essential
 - sudo apt-get install -qq devscripts
 - sudo apt-get install -qq dh-make    
 - sudo apt-get install -qq rpm    
