lang: c
script: ./travis-ci.sh
env:
  secure: "MDwmqlpHmEXFB2AcSPLeeRFGgvFy5iUxliMPsm21DdCna6lp8V4w2GiUTrAWo9oHqPuHtu+tQz6PuJ1JVX6Ui+JXz8pSKnnX8E3aBcHAxWGTNhOX4nFWWfrLu6gDSL4WusDBXmndAmtI/1sgJ3r40rPwZHiapg684beoClOkQXvbGS7CTwWrQN01F2ZpBq4Uytim4JEVx5Bx5z6KH24wi/iSAAiI+Ic1Tc9AEgWD+DNWF+iIUfbxZsBg/lF3xuKVAez+gyCVByWvv1isn2TuPaGvYhqPPNB/GqjsAzSmT35r8m3TIgGrmzM9WhGhs3HIXBL6uB1hDAVdQTHlUwZkexEmaTVpVJHEEcB4Qz2hjFUNQeJtv4oLQk20H12cRnTv+4vVoVHr5thFseU55vkv3wrw5VRB0pbcRqsD89jm64aPd9JINu8zios/3I47lqBtqX81KEbNqfZ4QmkWkVYqt7u8E9iw3f2BR/HGFFkGZUaLZFydPcGDjt3ZRSHfHfAAkUkvgZbYAzuZppZfRxH7jJetsh/jARVCfgAZRuH9P1s1vdA5hCVGRnrvy0uk5d/BnR1vhXo97gn37qxVN935v4rqPk/35+KVdQ75It7Vgq08tvrKwyQ0kOW3liUC9RTxmK5qJlIh6EOb8/uif2qUeyDt/iyo2MhLRyAgHzL2l9U="
notifications:
  irc:
    - "irc.freenode.org#rerun"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq markdown
 - sudo apt-get install -qq build-essential
 - sudo apt-get install -qq devscripts
 - sudo apt-get install -qq dh-make    
 - sudo apt-get install -qq rpm    
