#!/usr/bin/env bash

#/ command: rundeck-apitokens:create: "create a token"
#/ usage: rerun rundeck-apitokens:create  --token-user <>  --url <$RUNDECK_URL> [ --username <$RUNDECK_USER>] [ --password <$RUNDECK_PASSWORD>] [ --apikey <$RUNDECK_APIKEY>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: TOKEN_USER URL USERNAME PASSWORD APIKEY

. $RERUN_MODULE_DIR/lib/functions.sh create || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

CURL_OUT=$(mktemp -t curl.out.XXXXXXXXXX)
trap 'rm $CURL_OUT' EXIT; # cleanup on exit

rundeck_authenticate -u "$URL" -U "${USERNAME:-}" -p "${PASSWORD:-}" -k "${APIKEY:-}"
APIURL=${URL}/api/11/tokens/$TOKEN_USER
if ! http_code=$(rundeck_curl -w "%{http_code}" \
    -H 'Accept: application/xml' \
    -X POST "${APIURL}" -o $CURL_OUT)
then
	rerun_die 3 "curl request failed (exit code: $?)"
fi

#xmlstarlet fo $CURL_OUT

case ${http_code:-} in
	201) : ;; # successful
	40*) rerun_die 3 "$(xmlstarlet sel -t -m //error -v message $CURL_OUT)" ;;
	* ) rerun_die 3 "API error $http_code: POST ${APIURL})." ;;
esac  

xmlstarlet sel -t -m "//token[@user='$TOKEN_USER']" -v @id -n $CURL_OUT		

# Done. Exit with last command exit status.
exit $?

